"use client";
import {useState} from "react";
import type {BrokerObservationState} from "@/lib/broker-observation";

export function BrokerObservation({state,onAsk}:{state?:BrokerObservationState;onAsk:(prompt:string)=>void}) {
  const [query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[page,setPage]=useState(0),[selected,setSelected]=useState<string|null>(null);
  const report=state?.report,inspection=state?.inspection;
  const rows=(report?.orders||[]).filter(o=>(filter==="all"||o.status===filter)&&`${o.symbol} ${o.orderId} ${o.exchange} ${o.product}`.toLowerCase().includes(query.toLowerCase()));
  const maxPage=Math.max(0,Math.ceil(rows.length/10)-1), currentPage=Math.min(page,maxPage);
  const chosen=rows.find(o=>o.orderId===selected),trades=chosen?report?.trades.filter(t=>t.orderId===chosen.orderId):[];
  return <section className="panel portfolio-replay" aria-label="Broker order and trade observation">
    <div className="panel-title"><div><span className="eyebrow">EXTERNAL BROKER · READ ONLY</span><h2>Broker order &amp; trade checks</h2></div><span className="pill amber">{state?.status==="stale"?"Historical":state?.status==="available"?inspection?.status||"Unverified":"Unverified"}</span></div>
    <p className="research-notice">{state?.detail||"No external broker observation is configured."}</p>
    {report&&inspection&&<>
      <p className="muted">Kite · account reference {report.accountRef.slice(0,12)} · captured {new Date(report.finishedAt).toLocaleString()}. Capture window {((Date.parse(report.finishedAt)-Date.parse(report.startedAt))/1000).toFixed(1)}s.</p>
      <dl className="research-stats replay-metrics"><div><dt>Orders</dt><dd>{inspection.orderCount}</dd></div><div><dt>Executions</dt><dd>{inspection.tradeCount}</dd></div><div><dt>Nonterminal orders</dt><dd>{inspection.openOrderCount}</dd></div><div><dt>Observed issues</dt><dd>{inspection.issueCount}</dd></div></dl>
      {inspection.status==="changing"&&<p className="research-notice">Orders or trades changed between reads. Consistency is withheld; capture again after updates settle.</p>}
      {inspection.status==="empty"&&<p className="research-notice">No orders or trades were returned. Empty evidence does not qualify broker lifecycle handling.</p>}
      {!!inspection.issues.length&&<details open><summary>Inspect issues ({inspection.issues.length} of {inspection.issueCount})</summary><ul>{inspection.issues.map((i,n)=><li key={n}>{i.code.replaceAll("_"," ")}{i.orderId?` · ${i.orderId}`:""}</li>)}</ul></details>}
      <div className="replay-selectors"><label>Search broker orders<input aria-label="Search broker orders" value={query} placeholder="Symbol, order, exchange or product" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><label>Status<select aria-label="Broker order status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All statuses</option>{[...new Set(report.orders.map(o=>o.status))].sort().map(s=><option key={s}>{s}</option>)}</select></label></div><div className="research-actions"><a href="/api/broker/observation">Export evidence</a><button onClick={()=>onAsk("Explain the broker order/trade observation status, its issue codes, and what remains unverified before pilot launch. Keep this external observation separate from our paper-account records.")}>Ask Atlas</button></div>
      <div className="research-table-scroll" role="region" tabIndex={0} aria-label="Broker execution evidence"><table><thead><tr><th scope="col">Order / instrument</th><th scope="col">Status</th><th scope="col">Side / product</th><th scope="col">Requested</th><th scope="col">Filled</th><th scope="col">Pending</th><th scope="col">Cancelled</th><th scope="col">Evidence</th></tr></thead><tbody>{rows.slice(currentPage*10,currentPage*10+10).map(o=><tr key={o.orderId}><td><strong>{o.symbol}</strong><br/><small>{o.exchange} · {o.orderId}</small></td><td>{o.status}</td><td>{o.side} · {o.product}</td><td>{o.quantity}</td><td>{o.filled}</td><td>{o.pending}</td><td>{o.cancelled}</td><td><button aria-label={`Inspect broker order ${o.orderId}`} onClick={()=>setSelected(o.orderId)}>Inspect</button></td></tr>)}</tbody></table></div>
      {!rows.length&&<p className="empty">No broker orders match this view.</p>}
      <div className="replay-pagination"><button disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Previous orders</button><span>Page {currentPage+1} of {maxPage+1} · {rows.length} orders</span><button disabled={currentPage===maxPage} onClick={()=>setPage(currentPage+1)}>Next orders</button></div>
      {chosen&&<div className="callout"><h3>{chosen.symbol} · {chosen.orderId}</h3><p>Instrument {chosen.instrumentId} · {chosen.variety} · broker status {chosen.status}. Order registered {new Date(chosen.at).toLocaleString()}.</p><p>{chosen.status==="COMPLETE"?`Broker completion average: ${chosen.averagePrice}. Compared with execution-weighted price within 0.01 in the instrument's quote units.`:"Completion-average comparison does not apply to this status."}</p><div className="research-table-scroll" role="region" tabIndex={0} aria-label="Broker execution evidence"><table><thead><tr><th scope="col">Execution</th><th scope="col">Quantity</th><th scope="col">Price</th><th scope="col">Fill time</th></tr></thead><tbody>{trades?.slice(0,100).map(t=><tr key={`${t.exchange}:${t.tradeId}`}><td>{t.tradeId}</td><td>{t.quantity}</td><td>{t.price}</td><td>{new Date(t.at).toLocaleString()}</td></tr>)}</tbody></table></div><p>{trades?.length||0} linked executions; at most 100 displayed. Full evidence is available in the export.</p></div>}
      <p className="footnote">Consistency is agreement between repeated broker reads, not an atomic snapshot or proof of successful local execution. Cash, holdings, fees, lifecycle history and live/backtest parity are outside this check. Regular and AMO orders only; other varieties are flagged. No real orders can be placed here. Atlas receives counts and issue codes only.</p>
    </>}
  </section>;
}
