"use client";
import {useMemo,useState} from "react";
import {CartesianGrid,Legend,Line,LineChart,ReferenceDot,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import type {RunComparisonState} from "../lib/run-comparison-model";
const money=(v:string|number|null|undefined)=>v==null?"Unavailable":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v));
const pct=(v:string|undefined)=>v===undefined?"Unavailable":`${(Number(v)*100).toFixed(4)}%`;
export function RunComparison({state,onAsk}:{state?:RunComparisonState;onAsk:(prompt:string,sha:string)=>void}) {
 const [mode,setMode]=useState("equity"),[page,setPage]=useState(0),[selected,setSelected]=useState("");
 const [query,setQuery]=useState(""),[side,setSide]=useState("all"),[fillPage,setFillPage]=useState(0);
 const report=state?.report;
 const chart=useMemo(()=>report?.curve.map(p=>({minute:p.minute,paper:p.paper?.equity==null?null:mode==="equity"?Number(p.paper.equity):report.curve[0].paper?.equity?Number(p.paper.equity)/Number(report.curve[0].paper.equity)*100:null,replay:p.replay?.equity==null?null:mode==="equity"?Number(p.replay.equity):report.curve[0].replay?.equity?Number(p.replay.equity)/Number(report.curve[0].replay.equity)*100:null})),[report,mode]);
 const markers=useMemo(()=>{const byMinute=new Map(chart?.map(p=>[p.minute,p]));return report?.fillGroups.flatMap(g=>{const p=byMinute.get(g.minute);return (["paper","replay"] as const).flatMap(source=>g[source]&&p?.[source]!=null?[{minute:g.minute,value:p[source]!,source,side:g.side,key:`${g.minute}:${g.key}:${g.side}:${source}`}]:[]);}).slice(0,200)??[];},[report,chart]);
 const currentPage=Math.min(page,Math.max(0,Math.ceil((report?.curve.length??0)/10)-1));
 const chosen=report?.curve.find(p=>p.minute===selected)??report?.curve.at(-1);
 const groups=report?.fillGroups.filter(g=>(side==="all"||g.side===side)&&`${g.symbol} ${g.key}`.toLowerCase().includes(query.toLowerCase()))??[];
 const currentFillPage=Math.min(fillPage,Math.max(0,Math.ceil(groups.length/10)-1));
 return <section className="panel portfolio-replay" aria-label="Paper versus replay comparison">
  <div className="panel-title"><div><span className="eyebrow">RECORDED RUN DIAGNOSTICS</span><h2>Paper versus replay</h2></div><span className="pill amber">{report?"Unqualified comparison":state?.status??"Unavailable"}</span></div>
  <p className="research-notice">{state?.detail??"Publish a comparison of recorded paper observations and a retained historical replay to inspect execution and performance differences."}</p>
  {report&&<>
   <p className="muted">{new Date(report.window.start).toLocaleString()} to {new Date(report.window.end).toLocaleString()} (end excluded). {report.curve.length} expected regular-session minutes · allowed observation difference {report.window.maxSkewSeconds}s.</p>
   <dl className="research-stats replay-metrics"><div><dt>Paired minutes</dt><dd>{report.curve.filter(p=>!p.issues.length).length} / {report.curve.length}</dd></div><div><dt>Starting book</dt><dd>{report.initialState.replaceAll("_"," ")}</dd></div><div><dt>Paper return after recorded fees</dt><dd>{pct(report.metrics?.paperReturn)}</dd></div><div><dt>Historical replay return</dt><dd>{pct(report.metrics?.replayReturn)}</dd></div><div><dt>Ending equity difference</dt><dd>{money(report.metrics?.endingEquityDifference)}</dd></div><div><dt>Largest absolute equity difference</dt><dd>{money(report.metrics?.maxAbsoluteEquityDifference)}</dd></div></dl>
   <p className="research-notice">Strategy equivalence is unverified. Source inventory: {report.configuration.sourceComparison.replaceAll("_"," ")}. Different recorded components: {report.configuration.differentComponents.join(", ")||"none established"}. {report.configuration.observedUnqualifiedPoints} observed minutes lack an eligible strategy binding.</p>
   {!report.metrics&&<p role="status">Whole-window return and divergence statistics are withheld when observations are missing, invalid or outside the time tolerance, or fewer than two minutes are paired.</p>}
   <div className="replay-selectors"><label>Chart values<select aria-label="Run comparison chart" value={mode} onChange={e=>setMode(e.target.value)}><option value="equity">Equity in INR</option><option value="rebased">Rebased to 100</option></select></label></div>
   <div style={{height:260,minWidth:0,overflow:"hidden"}} role="group" aria-label="Recorded paper and replay equity curves with fill markers; missing observations leave gaps">
    <ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:0,right:16,top:12,bottom:4}}><CartesianGrid strokeDasharray="3 3" stroke="#27394b"/><XAxis dataKey="minute" minTickGap={45} tickFormatter={t=>new Date(t).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}/><YAxis domain={["auto","auto"]} width={65}/><Tooltip labelFormatter={t=>new Date(String(t)).toLocaleString()}/><Legend/><Line name="Recorded paper" dataKey="paper" stroke="#48c9b0" dot={false} connectNulls={false} isAnimationActive={false}/><Line name="Historical replay" dataKey="replay" stroke="#8d9dff" dot={false} connectNulls={false} isAnimationActive={false}/>{markers.map(m=><ReferenceDot key={m.key} x={m.minute} y={m.value} r={4} fill={m.side==="BUY"?"#e9ca78":"#ed8796"} stroke={m.source==="paper"?"#48c9b0":"#8d9dff"} shape={<circle role="button" tabIndex={0} style={{cursor:"pointer"}} aria-label={`Inspect ${m.source} ${m.side.toLowerCase()} fill at ${new Date(m.minute).toLocaleTimeString()}`} onClick={()=>setSelected(m.minute)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(m.minute);}}}/>}/>)}</LineChart></ResponsiveContainer>
   </div>
   <p className="footnote">Gold markers indicate buys; red markers indicate sells at the recorded equity in that minute, not at an execution-price axis. Up to 200 markers with available equity are shown; all selected fills remain in the evidence table/export. Values at different timestamps are not simultaneous marks. Gaps remain open, and a missing first observation withholds that run's rebased curve.</p>
   <details open><summary>Inspect paired minute evidence</summary><div className="research-table-scroll" role="region" tabIndex={0} aria-label="Paired run minutes"><table><thead><tr><th scope="col">Minute</th><th scope="col">Paper equity</th><th scope="col">Replay equity</th><th scope="col">Paper minus replay</th><th scope="col">Time difference</th><th scope="col">Coverage</th></tr></thead><tbody>{report.curve.slice(currentPage*10,currentPage*10+10).map(p=><tr key={p.minute}><th scope="row"><button aria-pressed={chosen?.minute===p.minute} onClick={()=>setSelected(p.minute)}>{new Date(p.minute).toLocaleTimeString()}</button></th><td>{money(p.paper?.equity)}</td><td>{money(p.replay?.equity)}</td><td>{money(p.equityDifference)}</td><td>{p.skewSeconds===null?"Unavailable":`${p.skewSeconds}s`}</td><td>{p.issues.map(i=>i.replaceAll("_"," ")).join(", ")||"Paired observations"}</td></tr>)}</tbody></table></div>
    <div className="replay-pagination"><button aria-label="Previous run comparison minutes" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {Math.max(1,Math.ceil(report.curve.length/10))}</span><button aria-label="Next run comparison minutes" disabled={(currentPage+1)*10>=report.curve.length} onClick={()=>setPage(currentPage+1)}>Next</button></div>
    {chosen&&<div className="callout"><h3>Selected minute · {new Date(chosen.minute).toLocaleString()}</h3><p>{chosen.issues.map(i=>i.replaceAll("_"," ")).join(" · ")||"Both observations meet the selected time tolerance."}</p>{(["paper","replay"] as const).map(source=><p key={source}>{source==="paper"?"Recorded paper":"Historical replay"}: {chosen[source]?`${new Date(chosen[source]!.at).toLocaleString()} · ledger ${chosen[source]!.ledgerId} · cash ${money(chosen[source]!.cash)} · ${chosen[source]!.holdings.length} valued holdings`:"No observation"}.</p>)}</div>}
   </details>
   <details open><summary>Inspect fill differences ({report.fills.paper.length} paper / {report.fills.replay.length} replay)</summary>
    <div className="replay-selectors"><label>Instrument<input aria-label="Search run comparison fills" value={query} onChange={e=>{setQuery(e.target.value);setFillPage(0);}}/></label><label>Side<select aria-label="Run comparison fill side" value={side} onChange={e=>{setSide(e.target.value);setFillPage(0);}}><option value="all">Both sides</option><option value="BUY">Buy</option><option value="SELL">Sell</option></select></label></div>
    <div className="research-table-scroll" role="region" tabIndex={0} aria-label="Run comparison fill groups"><table><thead><tr><th scope="col">Minute / instrument</th><th scope="col">Side</th><th scope="col">Paper qty / average</th><th scope="col">Replay qty / average</th><th scope="col">Quantity difference</th><th scope="col">Average-price difference</th><th scope="col">Recorded cash fees</th></tr></thead><tbody>{groups.slice(currentFillPage*10,currentFillPage*10+10).map(g=><tr key={`${g.minute}:${g.key}:${g.side}`}><th scope="row">{g.symbol}<br/><small>{new Date(g.minute).toLocaleTimeString()}</small></th><td>{g.side}</td><td>{g.paper?`${g.paper.quantity} / ${money(g.paper.averagePrice)}`:"No fills"}</td><td>{g.replay?`${g.replay.quantity} / ${money(g.replay.averagePrice)}`:"No fills"}</td><td>{g.quantityDifference}</td><td>{money(g.priceDifference)}</td><td>{money(g.paper?.cashFees)} / {money(g.replay?.cashFees)}</td></tr>)}</tbody></table></div>
    {!groups.length&&<p>No fill groups match this view.</p>}<div className="replay-pagination"><button disabled={!currentFillPage} onClick={()=>setFillPage(currentFillPage-1)}>Previous fill groups</button><span>{groups.length} groups</span><button disabled={(currentFillPage+1)*10>=groups.length} onClick={()=>setFillPage(currentFillPage+1)}>Next fill groups</button></div>
    <p className="footnote">Aggregated by minute, instrument and side. These are not one-to-one order matches or a causal explanation of divergence. Recorded cash fees are separate; spread/slippage already affect fill prices.</p>
   </details>
   <details><summary>Source and method</summary><p>Replay run {report.configuration.replayRunId} · protection {report.configuration.replayProtectionModel.replaceAll("_"," ")} · {report.window.excludedClosedMinutes} closed-market minutes outside the expected grid.</p><ul>{report.limitations.map(l=><li key={l}>{l}</li>)}</ul></details>
   <div className="research-actions"><a href={`/api/research/run-comparison?sha256=${state.sha256}`} download="pramana-run-comparison.json">Export run comparison</a><button onClick={()=>onAsk("Review this selected recorded paper versus historical replay comparison. Explain gaps, time differences, starting-book and recorded-configuration differences, equity divergence and fill-count limitations. Do not claim same-strategy, out-of-sample or launch qualification.",state.sha256!)}>Discuss run comparison with Atlas</button></div>
  </>}
 </section>;
}
